import type { Destination, Hotel, Package, Houseboat, Taxi, Activity } from "@/types/database"

// Mock destinations data
export const mockDestinations: Destination[] = [
  {
    id: "1",
    name: "Munnar",
    description: "Hill station known for its tea plantations and cool climate",
    location: "Idukki, Kerala",
    is_featured: true,
    image_url: "/placeholder.svg?key=h6dee",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Alleppey",
    description: "Famous for houseboats and backwaters",
    location: "Alappuzha, Kerala",
    is_featured: true,
    image_url: "/placeholder.svg?key=6l8tg",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Wayanad",
    description: "Known for wildlife sanctuaries and spice plantations",
    location: "Wayanad, Kerala",
    is_featured: true,
    image_url: "/placeholder.svg?key=tdhfu",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Thekkady",
    description: "Home to Periyar Wildlife Sanctuary",
    location: "Idukki, Kerala",
    is_featured: true,
    image_url: "/placeholder.svg?height=400&width=600&query=Thekkady+kerala",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Kovalam",
    description: "Beach destination with lighthouse",
    location: "Thiruvananthapuram, Kerala",
    is_featured: true,
    image_url: "/placeholder.svg?height=400&width=600&query=Kovalam+kerala",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Mock packages data
export const mockPackages: Package[] = [
  {
    id: "1",
    name: "Munnar + Thekkady",
    description: "Explore the hills and wildlife of Kerala",
    duration: "3N/4D",
    price: 12999,
    discount_percentage: 20,
    itinerary: null,
    inclusions: ["Accommodation", "Breakfast", "Sightseeing", "Transportation"],
    exclusions: ["Flights", "Personal expenses", "Optional activities"],
    images: ["/placeholder.svg?key=z8mgl"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Alleppey Houseboat Stay",
    description: "Experience the famous Kerala backwaters",
    duration: "1N/2D",
    price: 8499,
    discount_percentage: 15,
    itinerary: null,
    inclusions: ["Accommodation on houseboat", "All meals", "Cruise"],
    exclusions: ["Transportation to/from Alleppey", "Personal expenses"],
    images: ["/placeholder.svg?key=tyair"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Wayanad Adventure Trip",
    description: "Adventure and nature in the Western Ghats",
    duration: "2N/3D",
    price: 9999,
    discount_percentage: 10,
    itinerary: null,
    inclusions: ["Accommodation", "Breakfast", "Guided treks", "Safari"],
    exclusions: ["Flights", "Personal expenses", "Optional activities"],
    images: ["/placeholder.svg?height=400&width=600&query=Wayanad+adventure+package"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Mock hotels data
export const mockHotels: Hotel[] = [
  {
    id: "1",
    name: "Green Valley Resort",
    description: "Luxury resort with mountain views",
    destination_id: "1", // Munnar
    address: "Munnar, Kerala",
    price_per_night: 5999,
    star_rating: 4,
    amenities: ["WiFi", "Swimming Pool", "Restaurant", "Spa"],
    images: ["/placeholder.svg?height=400&width=600&query=Green+Valley+Resort+Munnar"],
    latitude: null,
    longitude: null,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Backwater Retreat",
    description: "Peaceful hotel by the backwaters",
    destination_id: "2", // Alleppey
    address: "Alleppey, Kerala",
    price_per_night: 4500,
    star_rating: 3,
    amenities: ["WiFi", "Restaurant", "Garden"],
    images: ["/placeholder.svg?height=400&width=600&query=Backwater+Retreat+Alleppey"],
    latitude: null,
    longitude: null,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Wayanad Wilderness",
    description: "Eco-friendly resort in the forest",
    destination_id: "3", // Wayanad
    address: "Wayanad, Kerala",
    price_per_night: 6500,
    star_rating: 4,
    amenities: ["WiFi", "Restaurant", "Outdoor Activities"],
    images: ["/placeholder.svg?height=400&width=600&query=Wayanad+Wilderness+Resort"],
    latitude: null,
    longitude: null,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Mock houseboats data
export const mockHouseboats: Houseboat[] = [
  {
    id: "1",
    name: "Premium Houseboat",
    description: "Luxury houseboat with AC bedrooms",
    location: "Alleppey",
    price_per_night: 15000,
    capacity: 6,
    bedrooms: 3,
    amenities: ["AC", "Kitchen", "Dining Area", "Sundeck"],
    images: ["/placeholder.svg?height=400&width=600&query=Premium+Houseboat+Alleppey"],
    is_luxury: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Standard Houseboat",
    description: "Comfortable houseboat for families",
    location: "Alleppey",
    price_per_night: 8000,
    capacity: 4,
    bedrooms: 2,
    amenities: ["Kitchen", "Dining Area", "Sundeck"],
    images: ["/placeholder.svg?height=400&width=600&query=Standard+Houseboat+Alleppey"],
    is_luxury: false,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Mock activities data
export const mockActivities: Activity[] = [
  {
    id: "1",
    name: "Kathakali Show",
    description: "Traditional Kerala dance performance",
    destination_id: "5", // Kovalam
    duration: "2 hours",
    price: 500,
    category: "Cultural",
    images: ["/placeholder.svg?height=400&width=600&query=Kathakali+Show+Kerala"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Periyar Wildlife Safari",
    description: "Boat safari in Periyar Tiger Reserve",
    destination_id: "4", // Thekkady
    duration: "3 hours",
    price: 1200,
    category: "Adventure",
    images: ["/placeholder.svg?height=400&width=600&query=Periyar+Wildlife+Safari"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Ayurvedic Spa Treatment",
    description: "Traditional Kerala ayurvedic massage",
    destination_id: "1", // Munnar
    duration: "1 hour",
    price: 2000,
    category: "Wellness",
    images: ["/placeholder.svg?height=400&width=600&query=Ayurvedic+Spa+Kerala"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Mock taxis data
export const mockTaxis: Taxi[] = [
  {
    id: "1",
    name: "Economy Sedan",
    description: "Comfortable sedan for city travel",
    vehicle_type: "Sedan",
    capacity: 4,
    price_per_km: 12,
    base_fare: 300,
    images: ["/placeholder.svg?height=400&width=600&query=Economy+Sedan+Taxi"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Premium SUV",
    description: "Spacious SUV for family travel",
    vehicle_type: "SUV",
    capacity: 6,
    price_per_km: 18,
    base_fare: 500,
    images: ["/placeholder.svg?height=400&width=600&query=Premium+SUV+Taxi"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Traveller Van",
    description: "Large van for group travel",
    vehicle_type: "Traveller",
    capacity: 12,
    price_per_km: 25,
    base_fare: 800,
    images: ["/placeholder.svg?height=400&width=600&query=Traveller+Van+Taxi"],
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
